export const data = [
  {
    id: 1,
    title: "Terminator",
    genre: "Action",
    numberInStock: 6,
    dailyRentalRate: 2.5,
    publishDate: "2018-01-03T19:04:28.809Z",
  },
  {
    id: 2,
    title: "Die Hard",
    genre: "Action",
    numberInStock: 5,
    dailyRentalRate: 2.5,
  },
  {
    id: 3,
    title: "Get Out",
    genre: "Thriller",
    numberInStock: 8,
    dailyRentalRate: 3.5,
  },
  {
    id: 4,
    title: "Trip to Italy",
    genre: "Comedy",
    numberInStock: 7,
    dailyRentalRate: 3.5,
  },
  {
    id: 5,
    title: "Airplane",
    genre: "Comedy",
    numberInStock: 7,
    dailyRentalRate: 3.5,
  },
  {
    id: 6,
    title: "Wedding Crashers",
    genre: "Comedy",
    numberInStock: 7,
    dailyRentalRate: 3.5,
  },
  {
    id: 7,
    title: "Gone Girl",
    genre: "Thriller",
    numberInStock: 7,
    dailyRentalRate: 4.5,
  },
  {
    id: 8,
    title: "The Sixth Sense",
    genre: "Thriller",
    numberInStock: 4,
    dailyRentalRate: 3.5,
  },
  {
    id: 9,
    title: "The Avengers",
    genre: "Action",
    numberInStock: 7,
    dailyRentalRate: 3.5,
  },
];
